info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true

zuul:
  server:
    route:
      stores: /stores
      customers: /customers

management:
  port: 8766

server:
  # moves the Spring Dispatch Servlet to a path below `/`
  servletPath: /app
  port: 8765
# sets the error path to use the Dispatch Servlet to resolve the error view
error:
  path: ${server.servletPath}/error

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
